// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmV-X_AOh_udh5cnQIKVywm_A64UcIowY',
    appId: '1:193972003939:web:2b03a668fcb9fbc8c70456',
    messagingSenderId: '193972003939',
    projectId: 'clearcodelab',
    authDomain: 'clearcodelab.firebaseapp.com',
    storageBucket: 'clearcodelab.appspot.com',
    measurementId: 'G-P6QLVQKPRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiztKUun9ITQtuZhxLH5K2FLDvb7keVFk',
    appId: '1:193972003939:android:3109ace9b2941d83c70456',
    messagingSenderId: '193972003939',
    projectId: 'clearcodelab',
    storageBucket: 'clearcodelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrB4qKB3FSipXkATWCe6h6iVn5oN51YmI',
    appId: '1:193972003939:ios:33eddb2b8b49c73cc70456',
    messagingSenderId: '193972003939',
    projectId: 'clearcodelab',
    storageBucket: 'clearcodelab.appspot.com',
    iosClientId: '193972003939-dl96ulrkqr3cohcrr69jkrpm0d4rri41.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseclass',
  );
}
